resources:
  - name: dependency-management-plugin
    type: git
    source:
      uri: https://github.com/spring-gradle-plugins/dependency-management-plugin
      branch: master
jobs:
  - name: build
    public: true
    plan:
    - get: dependency-management-plugin
      trigger: true
    - task: build
      file: dependency-management-plugin/ci/build.yml
  - name: deploy
    public: true
    plan:
    - get: dependency-management-plugin
      passed:
      - build
      trigger: true
    - task: deploy
      file: dependency-management-plugin/ci/deploy.yml
      params:
      - ARTIFACTORY_USERNAME: {{artifactory_username}}
      - ARTIFACTORY_PASSWORD: {{artifactory_password}}